apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
spec:
  type: NodePort
  selector:
    app: kafka-producer-ex
  ports:
    - port: 9191
      targetPort: 9191
      nodePort: 31471  # NodePort range is typically between 30000-32767

