apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: default
spec:
  clusterIP: None
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      name: client
